
export default {
    authenticated: false,
    userEmail: '',
    korisnickoIme:'',
    Dota: false,
    Csgo: false,
    Lol: false,
    lolodabir: false,
    dotaodabir: false,
    csgoodabir: false,
    dotaGameId:'',
    dotaRank:'',
    dotaPos:'',
    dotaRegija:'',
    csgoGameId:'',
    csgoRank:'',
    csgoPos:'',
    csgoRegija:'',
    lolGameId:'',
    lolRank:'',
    lolPos:'',
    lolRegija:'',
    Korisnici: [],
    imageData: null,
    prikazano: false,
    authUser: {},
    dotaChat:true,
    csgoChat:false,
    lolChat:false,
    messagedota:null,
    messagesdota:[],
    messagecsgo:null,
    messagescsgo:[],
    messagelol:null,
    messageslol:[],
    Komentari:[],
    Pozivi:[],
    loltim: false,
    dotatim: false,
    csgotim: false,
    dotaigraci: [],
    csgoigraci: [],
    loligraci: [],
    searchText: '',
    brc:0,
}